
services:
  web:
    image: makxies24/x3portfolio:latest
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: x3portfolio
    restart: always
    ports:
      - "3001:3001"