name: Build and Deploy Portfolio with three(3) version via Cloudflare SSH

on:
  push:
    branches: [ main ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- Docker build & push ----
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
            docker build \
            -f docker/Dockerfile \
            -t makxies24/x3portfolio:latest \
            .

      - name: Push Docker image
        run: |
          docker push makxies24/x3portfolio:latest

      # ---- Install cloudflared ----
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      # ---- Deploy via TCP ----
      - name: Deploy to Mini PC
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh \
            -i ~/.ssh/id_ed25519 \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -o ProxyCommand="cloudflared access tcp --hostname ssh.agriapp.site" \
            makxiesdell@ssh.agriapp.site \
            "
              cd /opt/apps/x3portfolio || exit 1
              docker pull makxies24/x3portfolio:latest
              docker compose up -d
              docker image prune -f
            "

            